### ISSUE TITLE
Can not get the Decoding time to under 278ms

### ISSUE THREAD

**Issue by sviseh** [CESNET/GPUJPEG#25] opened 2019-10-04 01:04 UTC
Hi, thanks for the interesting project.

I was comparing my results with the benchmark in the README and I have a hard time getting to less than ~278ms decode time. I am running my code on a 2070 super GPU. I was wondering if I am doing anything wrong or the numbers in the benchmark are referring to the in-GPU processing?

Decode Image GPU:         23.01 ms (only in-GPU processing)
Decode Image:            278.78 ms 

Thanks,
Sina

**Comment by MartinPulec** [comment] 2019-10-04 12:00
Hi Sina,

thanks for writing us - would it be possible to attach the image and how you decode it (eg. a command if you use the command-line application)? If you do so, I'd be able to rerun it and see if there is a problem with the image or you discovered some problem.

Generally speaking, if you test the command-line application for a single image, there may be a high penalty of initialization the CUDA device. Because using GPUJPEG usually doesn't make much sense for a single image, you may try also a `-n <count>` parameter to iterate over the image multiple times (for benchmarking).

Regards,
Martin

**Comment by sviseh** [comment] 2019-10-04 18:22
Hi Martin,

Thanks very much for the prompt response.

I followed your advised and placed the decode and encode process in a for loop and tried it for 2 different images and here is the results:
If I initialize the decoder, the out put is correct however the decoding time is around 270 ms. If I initialize the decoder, the performance is much better but I guess something goes wrong there since the out put is a gray solid color JPEG. 

sample1 and not decoder initialization
Avg decode time (ms) 268
Avg encode time (ms) 27

sample 2 and no decoder initialization
Avg decode time (ms) 323
Avg encode time (ms) 28

sample1
![sample_0_output_with_decoder_initialized](https://user-images.githubusercontent.com/4602012/66230475-1cdad900-e699-11e9-84ba-b041db3af7e3.jpg)
 and sample2 with decoder init
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
Avg decode time (ms) 26
Avg encode time (ms) 27

Please find 2 inout images and one output image attached. Also I am using this block of code for testing:
struct gpujpeg_parameters param;
gpujpeg_set_default_parameters(&param);
param.quality = 75;
param.restart_interval = 16;
param.interleaved = 1;

struct gpujpeg_image_parameters param_image;
gpujpeg_image_set_default_parameters(&param_image);

param_image.color_space = GPUJPEG_RGB;

if (gpujpeg_init_device(0, 0)) {
	printf("Failed to access devide id 0\n");
	return -1;
}

struct gpujpeg_encoder* encoder = gpujpeg_encoder_create(NULL);
if (encoder == NULL) {
	printf("Failed init encoder\n");
	return -1;
}

int image_size = 0;
uint8_t* image = NULL;

struct gpujpeg_decoder_output decoder_output;
gpujpeg_decoder_output_set_default(&decoder_output);

gpujpeg_decoder *decoder = gpujpeg_decoder_create(NULL);

param_image.width = 4096;
param_image.height = 4096;
param_image.comp_count = 3;
param_image.color_space = GPUJPEG_RGB;

// If I comment out the decoder initialization the output is correct but the decoding execution time is around 270ms
if (gpujpeg_decoder_init(decoder, &param, &param_image) != 0) {
	fprintf(stderr, "Failed to preinitialize decoder!\n");
	return -1;
}
// If I comment out the decoder initialization the output is correct but the decoding execution time is around 270ms

int totalDecode = 0;
int totalEncode = 0;

for (int i = 0; i < 20; i++) {
	if (gpujpeg_image_load_from_file("C:/Users/dev/Documents/Sina SandBox/layering/sample_4k_2.jpg", &image, &image_size) != 0) {
		fprintf(stderr, "Failed to load image [%s]!\n", "b&b");
		return -1;
	}

	auto start = std::chrono::steady_clock::now();

	if (gpujpeg_decoder_decode(decoder, image, image_size, &decoder_output) != 0) {
		fprintf(stderr, "Failed to decode image [%s]!\n", "b&b");
		return -1;
	}

	auto end = std::chrono::steady_clock::now();
	auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
	totalDecode += elapsed.count();

	struct gpujpeg_encoder_input encoder_input;
	gpujpeg_encoder_input_set_image(&encoder_input, decoder_output.data);

	uint8_t* image_compressed = NULL;
	int image_compressed_size = 0;

	start = std::chrono::steady_clock::now();

	if (gpujpeg_encoder_encode(encoder, &param, &param_image, &encoder_input, &image_compressed, &image_compressed_size) != 0) {
		printf("Failed to encode image [%s]!\n", "b&b.jpg");
		return -1;
	}

	end = std::chrono::steady_clock::now();
	elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
	totalEncode += elapsed.count();
	//printf("GPU encoding time (ms) %d \n", elapsed.count());

	string base = "C:/Users/dev/Documents/Sina SandBox/layering/test/sample_"+ to_string(i) + ".jpg";
	if (gpujpeg_image_save_to_file(base.c_str(), image_compressed, image_compressed_size) != 0) {
		printf("Failed to save gpu encoded image\n");
		return -1;
	}
}

printf("Avg decode time (ms) %d \n", totalDecode / 20);
printf("Avg encode time (ms) %d \n", totalEncode / 20);

gpujpeg_decoder_destroy(decoder);
gpujpeg_encoder_destroy(encoder);

Thanks!
Sina
![sample2](https://user-images.githubusercontent.com/4602012/66230527-3a0fa780-e699-11e9-8438-11dcd4a70eb5.jpg)
![sample1](https://user-images.githubusercontent.com/4602012/66230529-3a0fa780-e699-11e9-8866-b2ce04f7b654.jpg)

**Comment by sviseh** [comment] 2019-10-04 18:25
Hi Martin,

Thanks very much for the prompt response.

I followed your advised and placed the decode and encode process in a for loop and tried it for 2 different images and here is the results:
If I initialize the decoder, the out put is correct however the decoding time is around 270 ms. If I initialize the decoder, the performance is much better but I guess something goes wrong there since the out put is a gray solid color JPEG.

sample1 and no decoder initialization
Avg decode time (ms) 268
Avg encode time (ms) 27

sample 2 and no decoder initialization
Avg decode time (ms) 323
Avg encode time (ms) 28

sample1 and sample2 with decoder init
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
Avg decode time (ms) 26
Avg encode time (ms) 27

Please find 2 input images and one output image attached. Also I am using this block of code for testing:

struct gpujpeg_parameters param;
gpujpeg_set_default_parameters(&param);
param.quality = 75;
param.restart_interval = 16;
param.interleaved = 1;

struct gpujpeg_image_parameters param_image;
gpujpeg_image_set_default_parameters(&param_image);

param_image.color_space = GPUJPEG_RGB;

if (gpujpeg_init_device(0, 0)) {
	printf("Failed to access devide id 0\n");
	return -1;
}

struct gpujpeg_encoder* encoder = gpujpeg_encoder_create(NULL);
if (encoder == NULL) {
	printf("Failed init encoder\n");
	return -1;
}

int image_size = 0;
uint8_t* image = NULL;

struct gpujpeg_decoder_output decoder_output;
gpujpeg_decoder_output_set_default(&decoder_output);

gpujpeg_decoder *decoder = gpujpeg_decoder_create(NULL);

param_image.width = 4096;
param_image.height = 4096;
param_image.comp_count = 3;
param_image.color_space = GPUJPEG_RGB;

// If I comment out the decoder initialization the output is correct but the decoding execution time is around 270ms
if (gpujpeg_decoder_init(decoder, &param, &param_image) != 0) {
	fprintf(stderr, "Failed to preinitialize decoder!\n");
	return -1;
}
// If I comment out the decoder initialization the output is correct but the decoding execution time is around 270ms

int totalDecode = 0;
int totalEncode = 0;

for (int i = 0; i < 20; i++) {
	if (gpujpeg_image_load_from_file("C:/Users/dev/Documents/Sina SandBox/layering/sample_4k_2.jpg", &image, &image_size) != 0) {
		fprintf(stderr, "Failed to load image [%s]!\n", "b&b");
		return -1;
	}

	auto start = std::chrono::steady_clock::now();

	if (gpujpeg_decoder_decode(decoder, image, image_size, &decoder_output) != 0) {
		fprintf(stderr, "Failed to decode image [%s]!\n", "b&b");
		return -1;
	}

	auto end = std::chrono::steady_clock::now();
	auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
	totalDecode += elapsed.count();

	struct gpujpeg_encoder_input encoder_input;
	gpujpeg_encoder_input_set_image(&encoder_input, decoder_output.data);

	uint8_t* image_compressed = NULL;
	int image_compressed_size = 0;

	start = std::chrono::steady_clock::now();

	if (gpujpeg_encoder_encode(encoder, &param, &param_image, &encoder_input, &image_compressed, &image_compressed_size) != 0) {
		printf("Failed to encode image [%s]!\n", "b&b.jpg");
		return -1;
	}

	end = std::chrono::steady_clock::now();
	elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
	totalEncode += elapsed.count();
	//printf("GPU encoding time (ms) %d \n", elapsed.count());

	string base = "C:/Users/dev/Documents/Sina SandBox/layering/test/sample_"+ to_string(i) + ".jpg";
	if (gpujpeg_image_save_to_file(base.c_str(), image_compressed, image_compressed_size) != 0) {
		printf("Failed to save gpu encoded image\n");
		return -1;
	}
}

printf("Avg decode time (ms) %d \n", totalDecode / 20);
printf("Avg encode time (ms) %d \n", totalEncode / 20);

gpujpeg_decoder_destroy(decoder);
gpujpeg_encoder_destroy(encoder);


![sample2](https://user-images.githubusercontent.com/4602012/66230736-a68aa680-e699-11e9-9869-ef7f69e2c542.jpg)
![sample1](https://user-images.githubusercontent.com/4602012/66230737-a68aa680-e699-11e9-8bfa-55f99287245d.jpg)
![sample_0_output_with_decoder_initialized](https://user-images.githubusercontent.com/4602012/66230738-a68aa680-e699-11e9-886c-bda3f6fd2e5b.jpg)

Thanks!
Sina

**Comment by sviseh** [comment] 2019-10-04 18:30
Hi Martin,

Thanks very much for the prompt response.

I followed your advised and placed the decode and encode process in a for loop and tried it for 2 different images and here is the results:
If I initialize the decoder, the out put is correct however the decoding time is around 270 ms. If I initialize the decoder, the performance is much better but I guess something goes wrong there since the out put is a gray solid color JPEG.

sample1 and no decoder initialization
Avg decode time (ms) 268
Avg encode time (ms) 27

sample 2 and no decoder initialization
Avg decode time (ms) 323
Avg encode time (ms) 28

sample1 and sample2 with decoder init
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
Avg decode time (ms) 26
Avg encode time (ms) 27

Please find 2 input images and one output image attached. Also I am using this block of code for testing:

int testGPUEncoder() {
	struct gpujpeg_parameters param;
	gpujpeg_set_default_parameters(&param);
	param.quality = 75;
	param.restart_interval = 16;
	param.interleaved = 1;

	struct gpujpeg_image_parameters param_image;
	gpujpeg_image_set_default_parameters(&param_image);

	param_image.color_space = GPUJPEG_RGB;

	if (gpujpeg_init_device(0, 0)) {
		printf("Failed to access devide id 0\n");
		return -1;
	}

	struct gpujpeg_encoder* encoder = gpujpeg_encoder_create(NULL);
	if (encoder == NULL) {
		printf("Failed init encoder\n");
		return -1;
	}

	int image_size = 0;
	uint8_t* image = NULL;

	struct gpujpeg_decoder_output decoder_output;
	gpujpeg_decoder_output_set_default(&decoder_output);

	gpujpeg_decoder *decoder = gpujpeg_decoder_create(NULL);

	param_image.width = 4096;
	param_image.height = 4096;
	param_image.comp_count = 3;
	param_image.color_space = GPUJPEG_RGB;

	if (gpujpeg_decoder_init(decoder, &param, &param_image) != 0) {
		fprintf(stderr, "Failed to preinitialize decoder!\n");
		return -1;
	}

	int totalDecode = 0;
	int totalEncode = 0;

	for (int i = 0; i < 20; i++) {
		if (gpujpeg_image_load_from_file("C:/Users/dev/Documents/Sina SandBox/layering/sample_4k_2.jpg", &image, &image_size) != 0) {
			fprintf(stderr, "Failed to load image [%s]!\n", "b&b");
			return -1;
		}

		auto start = std::chrono::steady_clock::now();

		if (gpujpeg_decoder_decode(decoder, image, image_size, &decoder_output) != 0) {
			fprintf(stderr, "Failed to decode image [%s]!\n", "b&b");
			return -1;
		}

		auto end = std::chrono::steady_clock::now();
		auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
		totalDecode += elapsed.count();

		struct gpujpeg_encoder_input encoder_input;
		gpujpeg_encoder_input_set_image(&encoder_input, decoder_output.data);

		uint8_t* image_compressed = NULL;
		int image_compressed_size = 0;

		start = std::chrono::steady_clock::now();

		if (gpujpeg_encoder_encode(encoder, &param, &param_image, &encoder_input, &image_compressed, &image_compressed_size) != 0) {
			printf("Failed to encode image [%s]!\n", "b&b.jpg");
			return -1;
		}

		end = std::chrono::steady_clock::now();
		elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
		totalEncode += elapsed.count();
		//printf("GPU encoding time (ms) %d \n", elapsed.count());

		string base = "C:/Users/dev/Documents/Sina SandBox/layering/test/sample_" + to_string(i) + ".jpg";
		if (gpujpeg_image_save_to_file(base.c_str(), image_compressed, image_compressed_size) != 0) {
			printf("Failed to save gpu encoded image\n");
			return -1;
		}
	}

	printf("Avg decode time (ms) %d \n", totalDecode / 20);
	printf("Avg encode time (ms) %d \n", totalEncode / 20);

	gpujpeg_decoder_destroy(decoder);
	gpujpeg_encoder_destroy(encoder);

	return 1;
}

![sample2](https://user-images.githubusercontent.com/4602012/66231033-53fdba00-e69a-11e9-99a6-3150e0e6ba5a.jpg)
![sample1](https://user-images.githubusercontent.com/4602012/66231034-53fdba00-e69a-11e9-88c4-39384369bed1.jpg)
![sample_0_output_with_decoder_initialized](https://user-images.githubusercontent.com/4602012/66231035-54965080-e69a-11e9-89e3-1114251028d9.jpg)

Thanks!
Sina

**Comment by sviseh** [comment] 2019-10-04 18:32
Hi Martin,

Thanks very much for the prompt response.

I followed your advised and placed the decode and encode process in a for loop and tried it for 2 different images and here is the results:
If I initialize the decoder, the out put is correct however the decoding time is around 270 ms. If I initialize the decoder, the performance is much better but I guess something goes wrong there since the out put is a gray solid color JPEG.

sample1 and no decoder initialization
Avg decode time (ms) 268
Avg encode time (ms) 27

sample 2 and no decoder initialization
Avg decode time (ms) 323
Avg encode time (ms) 28

sample1 and sample2 with decoder init
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
[GPUJPEG] [Error] Can't reinitialize decoder, implement if needed!
Avg decode time (ms) 26
Avg encode time (ms) 27

Please find 2 input images and one output image attached. Also I am using this block of code for testing:

int testGPUEncoder() {
	struct gpujpeg_parameters param;
	gpujpeg_set_default_parameters(&param);
	param.quality = 75;
	param.restart_interval = 16;
	param.interleaved = 1;

	struct gpujpeg_image_parameters param_image;
	gpujpeg_image_set_default_parameters(&param_image);

	param_image.color_space = GPUJPEG_RGB;

	if (gpujpeg_init_device(0, 0)) {
		printf("Failed to access devide id 0\n");
		return -1;
	}

	struct gpujpeg_encoder* encoder = gpujpeg_encoder_create(NULL);
	if (encoder == NULL) {
		printf("Failed init encoder\n");
		return -1;
	}

	int image_size = 0;
	uint8_t* image = NULL;

	struct gpujpeg_decoder_output decoder_output;
	gpujpeg_decoder_output_set_default(&decoder_output);

	gpujpeg_decoder *decoder = gpujpeg_decoder_create(NULL);

	param_image.width = 4096;
	param_image.height = 4096;
	param_image.comp_count = 3;
	param_image.color_space = GPUJPEG_RGB;

	if (gpujpeg_decoder_init(decoder, &param, &param_image) != 0) {
		fprintf(stderr, "Failed to preinitialize decoder!\n");
		return -1;
	}

	int totalDecode = 0;
	int totalEncode = 0;

	for (int i = 0; i < 20; i++) {
		if (gpujpeg_image_load_from_file("C:/Users/dev/Documents/test/sample_2.jpg", &image, &image_size) != 0) {
			fprintf(stderr, "Failed to load image [%s]!\n", "b&b");
			return -1;
		}

		auto start = std::chrono::steady_clock::now();

		if (gpujpeg_decoder_decode(decoder, image, image_size, &decoder_output) != 0) {
			fprintf(stderr, "Failed to decode image [%s]!\n", "b&b");
			return -1;
		}

		auto end = std::chrono::steady_clock::now();
		auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
		totalDecode += elapsed.count();

		struct gpujpeg_encoder_input encoder_input;
		gpujpeg_encoder_input_set_image(&encoder_input, decoder_output.data);

		uint8_t* image_compressed = NULL;
		int image_compressed_size = 0;

		start = std::chrono::steady_clock::now();

		if (gpujpeg_encoder_encode(encoder, &param, &param_image, &encoder_input, &image_compressed, &image_compressed_size) != 0) {
			printf("Failed to encode image [%s]!\n", "b&b.jpg");
			return -1;
		}

		end = std::chrono::steady_clock::now();
		elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(end - start);
		totalEncode += elapsed.count();
		//printf("GPU encoding time (ms) %d \n", elapsed.count());

		string base = "C:/Users/dev/Documents/test/sample_" + to_string(i) + ".jpg";
		if (gpujpeg_image_save_to_file(base.c_str(), image_compressed, image_compressed_size) != 0) {
			printf("Failed to save gpu encoded image\n");
			return -1;
		}
	}

	printf("Avg decode time (ms) %d \n", totalDecode / 20);
	printf("Avg encode time (ms) %d \n", totalEncode / 20);

	gpujpeg_decoder_destroy(decoder);
	gpujpeg_encoder_destroy(encoder);

	return 1;
}

Thanks!
Sina

![sample2](https://user-images.githubusercontent.com/4602012/66231124-8b6c6680-e69a-11e9-9662-d206a8951c45.jpg)
![sample1](https://user-images.githubusercontent.com/4602012/66231125-8c04fd00-e69a-11e9-83ed-e03b8eb9bf0b.jpg)
![sample_0_output_with_decoder_initialized](https://user-images.githubusercontent.com/4602012/66231126-8c04fd00-e69a-11e9-9e1b-766c4cedd180.jpg)

**Comment by MartinPulec** [comment] 2019-10-07 16:22
Hi Sina,

okay, I've following remarks:

- I've checked the code and for the initialization you need to correctly set `width` `height` and `comp_count`, `restart_interval`, `interleaved` and horizontal/vertical subsampling for all components. That is a bit tricky, maybe it would be sufficient to call only `gpujpeg_init_device` prior the computation or pass one image through the decoder to init.

- However, it doesn't seem that the decoder initialization duration is the issue because when initialized implicitly, the decoder initializes itself only once, so it would definitely amortize within 20 iterations

- the gray decoding is definitely incorrect - the decode function just doesn't return an error value as it should, I've already fixed that.

The main problem, however, is with the image itself because it doesn't use restart intervals and therefore the Huffman decoder is run sequentially on CPU which is the major bottleneck (you can see profiling if you set gpujpeg_parameters::verbose to true - or you can use `-v` parameter with the testing app). I got something like this with a card from a first generation of Titan:
```
Iteration #50:
 -Stream Reader:           3.97 ms
 -Huffman CPU Decoder:    98.13 ms
 -Copy From Device:        4.27 ms
Decode Image GPU:          7.46 ms (only in-GPU processing)
Decode Image:            113.88 ms
```

**Comment by MartinPulec** [comment] 2019-10-30 13:09
Closing the issue because the problem is not solvable inside UltraGrid - apart from some optimization of the CPU Huffman decoder (it is question how efficient it is). Another possibility could be a hybrid CPU/GPU Huffman decoder (DC part needs to be decoded on CPU, because it is sequential, ACs may be possible to deploy on GPU). But this would require additional effort.

 Reopen if you have some update.

**Closed by MartinPulec** 2019-10-30 13:09 UTC
